/// <summary>
/// Represents the data required to create a new user profile.
/// </summary>
/// <remarks>
/// This DTO is the API's request contract for creating a user profile. It
/// intentionally omits <c>Id</c>, since the identifier is generated by the
/// database on insert and must not be supplied by the caller.
/// </remarks>

namespace ReviewAPI.Dtos
{
    public class CreateUserProfileDto
    {
        public required string UserName { get; init; }
        public string? Email { get; init; }
        public string? PhoneNumber { get; init; }
        public string? Country { get; init; }
    }
}
